# ***Опис проєкту:***

ДатаСет містить інформацію щодо продажів продукції компанії, яка працює на світовому ринку і продає товари у звичайних магазинах та інтернет-магазинах. Датасет складається з 3-х таблиць:


---

1. ***events.csv*** — продажі за декілька років, дає інформацію про дії користувачів (події). Складається з 1330 записів та 10 змінних:

***Order ID:*** id замовлення;

***Order Date:*** дата замовлення;

***Ship Date:*** дата відвавнтаження;

***Order Priority:*** пріорітет замовлення;

***Country Code:*** код країни;

***Product ID:***	id товару;

***Sales Channel:*** канал продажу;

***Units Sold:*** кількість проданих одиниць товару;

***Unit Price:***	ціна за одиницю товару;

***Unit Cost:*** витрат на одиницю товару.


---


2. ***products.csv*** — категорії товарів та їх коди, деталізує характеристики продуктів. Складається з 12 записів та 2 змінні:

***id:*** id товару;

***item_type:*** вид товару.



---


3. ***countries.csv*** — країни, регіони та їх коди, додає географічний контекст через коди країн. Складається з 249 записів та 5 змінних:

***name:*** назва країни;

***alpha-2:***	двосимвольний код країни;

***alpha-3:***	трьосимвольний код країни;

***region:***	назва регіону;

***sub-region:*** назва субрегіону.


---


***Основна мета завдання:***

*  очищення даних та проведення їх аналізу;

* знаходження цінних інсайтів діяльності компанії.

# ***Етапи проєкту:***

# ***1. Data overview. Розуміння даних та їх змісту***



* Завантаж датасет, розберись зі змістом колонок, зроби їх опис.

* Вияви ключові поля, що поєднують три таблиці.

In [1]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
file_path_events = '/content/drive/My Drive/events.csv'
df_events = pd.read_csv(file_path_events)
df_events

,Order ID,Order Date,Ship Date,Order Priority,Country Code,Product ID,Sales Channel,Units Sold,Unit Price,Unit Cost
0,100640618,10/8/2014,10/18/2014,M,NOR,2103,Online,650.0,205.70,117.11
1,100983083,8/11/2016,8/11/2016,C,SRB,2103,Offline,1993.0,205.70,117.11
2,101025998,7/18/2014,8/11/2014,M,NaN,7940,Online,4693.0,668.27,502.54
3,102230632,5/13/2017,6/13/2017,L,MNE,2455,Online,1171.0,109.28,35.84
4,103435266,8/11/2012,9/18/2012,H,SRB,1270,Offline,7648.0,47.45,31.79
...,...,...,...,...,...,...,...,...,...,...
1325,994504153,1/10/2017,1/13/2017,M,SWE,4594,Online,4734.0,9.33,6.92
1326,994978797,12/5/2014,1/2/2015,H,ITA,1270,Offline,5192.0,47.45,31.79
1327,996754205,9/20/2010,9/22/2010,L,RUS,7331,Offline,574.0,255.28,159.42
1328,998043382,6/15/2010,7/3/2010,H,MLT,8293,Online,2070.0,437.20,263.33
1329,999879729,3/31/2012,5/6/2012,M,ALB,7940,Offline,5486.0,668.27,502.54

In [3]:
file_path_products = '/content/drive/My Drive/products.csv'
df_products = pd.read_csv(file_path_products)
df_products

      id        item_type
0   2103           Cereal
1   7940        Household
2   2455          Clothes
3   1270        Beverages
4   8681  Office Supplies
5   4594           Fruits
6   5988       Vegetables
7   7331        Baby Food
8   8875             Meat
9   8293        Cosmetics
10  8969           Snacks
11  3127    Personal Care

In [4]:
file_path_countries = '/content/drive/My Drive/countries.csv'
df_countries = pd.read_csv(file_path_countries)
df_countries

                  name alpha-2 alpha-3   region          sub-region
0          Afghanistan      AF     AFG     Asia       Southern Asia
1        Åland Islands      AX     ALA   Europe     Northern Europe
2              Albania      AL     ALB   Europe     Southern Europe
3              Algeria      DZ     DZA   Africa     Northern Africa
4       American Samoa      AS     ASM  Oceania           Polynesia
..                 ...     ...     ...      ...                 ...
244  Wallis and Futuna      WF     WLF  Oceania           Polynesia
245     Western Sahara      EH     ESH   Africa     Northern Africa
246              Yemen      YE     YEM     Asia        Western Asia
247             Zambia      ZM     ZMB   Africa  Sub-Saharan Africa
248           Zimbabwe      ZW     ZWE   Africa  Sub-Saharan Africa

[249 rows x 5 columns]

✅ ***Вияви ключові поля, що поєднують три таблиці:***

1. events.csv 🆚 products.csv


поле ***"Product ID"*** у таблиці ***events.csv*** відповідає полю ***"id"*** у таблиці ***products.csv***


---




2. events.csv 🆚 countries.csv

поле ***"Country Code"*** у таблиці ***countries.csv*** відповідає полю ***"alpha-3"*** у таблиці ***countries.csv***

# ***2. Data cleaning. Робота із пропущеними даними, некоректними даними, аномаліями.***


* Подивись, чи є пропущені значення у кожній таблиці, оціни їх долю, спробуй зрозуміти причини їх виникнення.

* Заповни або видали пропущені значення, обґрунтувавши свою думку.
Подивись, чи всі типи даних розпізнаються коректно. Якщо є розбіжності, потрібно виявити та усунути причини, за потреби, зробити перетворення типів у колонках.

* Досліди дані на наявність дублікатів. Зверни увагу, що дублікати можуть траплятися через зайві пробіли (або інші символи) у комірках, розбіжність у великих/малих літерах, схожість літер у кирилиці/латиниці тощо. За потреби, зроби перетворення для усунення дублікатів.

* Досліди дані на наявність аномалій. Якщо є, спробуй зрозуміти причини.

##***events***

🔷 ***Подивись, чи є пропущені значення у кожній таблиці, оціни їх долю, спробуй зрозуміти причини їх виникнення.***

In [5]:
df_events.isna().sum()

Order ID           0
Order Date         0
Ship Date          0
Order Priority     0
Country Code      82
Product ID         0
Sales Channel      0
Units Sold         2
Unit Price         0
Unit Cost          0
dtype: int64

📌 ***Доля пропущених значення events.csv***

In [6]:
missing_counts_events = df_events.isna().sum()
print("Пропущені значення:", missing_counts_events)

missing_percent_events = df_events.isna().mean() * 100
print("\nДоля пропущених значення:", missing_percent_events)

Пропущені значення: Order ID           0
Order Date         0
Ship Date          0
Order Priority     0
Country Code      82
Product ID         0
Sales Channel      0
Units Sold         2
Unit Price         0
Unit Cost          0
dtype: int64

Доля пропущених значення: Order ID          0.000000
Order Date        0.000000
Ship Date         0.000000
Order Priority    0.000000
Country Code      6.165414
Product ID        0.000000
Sales Channel     0.000000
Units Sold        0.150376
Unit Price        0.000000
Unit Cost         0.000000
dtype: float64

In [7]:
missing_sumup_events = pd.DataFrame({"missing_counts_events": round(missing_counts_events, 2), "missing_percent_events": round(missing_percent_events, 2)})

print(missing_sumup_events)

                missing_counts_events  missing_percent_events
Order ID                            0                    0.00
Order Date                          0                    0.00
Ship Date                           0                    0.00
Order Priority                      0                    0.00
Country Code                       82                    6.17
Product ID                          0                    0.00
Sales Channel                       0                    0.00
Units Sold                          2                    0.15
Unit Price                          0                    0.00
Unit Cost                           0                    0.00

In [8]:
df_events[df_events.isna().any(axis=1)].head(84)

,Order ID,Order Date,Ship Date,Order Priority,Country Code,Product ID,Sales Channel,Units Sold,Unit Price,Unit Cost
2,101025998,7/18/2014,8/11/2014,M,NaN,7940,Online,4693.0,668.27,502.54
13,104548490,1/1/2014,1/5/2014,M,NaN,7331,Online,7076.0,255.28,159.42
26,117929494,1/24/2015,3/2/2015,H,NaN,4594,Offline,6813.0,9.33,6.92
29,118859469,6/2/2011,7/1/2011,L,NaN,8969,Offline,2013.0,152.58,97.44
43,126948583,5/24/2017,7/9/2017,C,NaN,7331,Online,5762.0,255.28,159.42
...,...,...,...,...,...,...,...,...,...,...
1213,919922006,8/27/2011,9/18/2011,L,NaN,4594,Online,4219.0,9.33,6.92
1220,922564303,3/17/2017,4/2/2017,L,NaN,7940,Offline,6134.0,668.27,502.54
1250,941061675,3/8/2017,3/20/2017,M,NaN,5988,Offline,9917.0,154.06,90.93
1296,975080668,7/23/2017,8/20/2017,C,NaN,5988,Offline,6893.0,154.06,90.93
1317,989102828,6/11/2012,7/8/2012,L,NaN,4594,Online,6362.0,9.33,6.92

🔷 ***видалення пропущених значень в стовпці*** ***`Units Sold'`***

In [9]:
df_events = df_events.dropna(subset=['Units Sold'])

✅ ***Обгрунтування видалення пропущених значень в стовці `Units Sold`:***

* не викривляє загальну статистику, відсутніх даних ~ 0.15%.

🔷 ***Заповнення відсутніх значень в стовпці*** ***`Country Code`***

In [10]:
df_events = df_events.copy()
df_events["Country Code"] = df_events["Country Code"].fillna("Unknown")

✅ ***Обгрунтування заповнення пропущених значень в стовці `Country Code`:***

* враховуючи те, що частка відсутніх значень ~ 6%, видалення їх не бажано, тому що це може призвести до спотворення загального результату аналізу;

* доцільно, заповнити значенням - `Unknown`. Маніпуляції з даними збережуть записи у вибірці, уникнут викривлення статистики.

In [11]:
df_events.isna().sum()

Order ID          0
Order Date        0
Ship Date         0
Order Priority    0
Country Code      0
Product ID        0
Sales Channel     0
Units Sold        0
Unit Price        0
Unit Cost         0
dtype: int64



---

In [12]:
df_events.head()

,Order ID,Order Date,Ship Date,Order Priority,Country Code,Product ID,Sales Channel,Units Sold,Unit Price,Unit Cost
0,100640618,10/8/2014,10/18/2014,M,NOR,2103,Online,650.0,205.70,117.11
1,100983083,8/11/2016,8/11/2016,C,SRB,2103,Offline,1993.0,205.70,117.11
2,101025998,7/18/2014,8/11/2014,M,Unknown,7940,Online,4693.0,668.27,502.54
3,102230632,5/13/2017,6/13/2017,L,MNE,2455,Online,1171.0,109.28,35.84
4,103435266,8/11/2012,9/18/2012,H,SRB,1270,Offline,7648.0,47.45,31.79

In [13]:
df_events.isna().sum()

Order ID          0
Order Date        0
Ship Date         0
Order Priority    0
Country Code      0
Product ID        0
Sales Channel     0
Units Sold        0
Unit Price        0
Unit Cost         0
dtype: int64



---

🔷 ***Подивись, чи всі типи даних розпізнаються коректно. Якщо є розбіжності, потрібно виявити та усунути причини, за потреби, зробити перетворення типів у колонках***

In [14]:
df_events.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1328 entries, 0 to 1329
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        1328 non-null   int64
 1   Order Date      1328 non-null   object
 2   Ship Date       1328 non-null   object
 3   Order Priority  1328 non-null   object
 4   Country Code    1328 non-null   object
 5   Product ID      1328 non-null   int64
 6   Sales Channel   1328 non-null   object
 7   Units Sold      1328 non-null   float64
 8   Unit Price      1328 non-null   float64
 9   Unit Cost       1328 non-null   float64
dtypes: float64(3), int64(2), object(5)
memory usage: 146.4+ KB

✅ тип даних в стовпцях ***`Order Date`,	`Ship Date`*** - `object`, потрібно змінити на тип даних - ***datetime***

✅ тип даних в стовпці ***`Units Sold`*** - `float64`, доцільно змінити на ціле число `int64`

In [15]:
df_events["Order Date"] = pd.to_datetime(df_events["Order Date"], errors="coerce")
df_events["Ship Date"] = pd.to_datetime(df_events["Ship Date"], errors="coerce")
df_events["Units Sold"] = df_events["Units Sold"].astype('int64')

In [16]:
df_events.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1328 entries, 0 to 1329
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        1328 non-null   int64
 1   Order Date      1328 non-null   datetime64[ns]
 2   Ship Date       1328 non-null   datetime64[ns]
 3   Order Priority  1328 non-null   object
 4   Country Code    1328 non-null   object
 5   Product ID      1328 non-null   int64
 6   Sales Channel   1328 non-null   object
 7   Units Sold      1328 non-null   int64
 8   Unit Price      1328 non-null   float64
 9   Unit Cost       1328 non-null   float64
dtypes: datetime64[ns](2), float64(2), int64(3), object(3)
memory usage: 146.4+ KB

🔷 ***Досліди дані на наявність дублікатів***

In [17]:
cols_to_clean = ["Order Priority", "Country Code", "Sales Channel"]

for i in cols_to_clean:
  df_events[i] = df_events[i].str.strip().str.title()

In [18]:
for i in cols_to_clean:
  print(f"Унікальні значення в '{i}': ")
  print(df_events[i].unique())
  print("\n")

Унікальні значення в 'Order Priority':
['M' 'C' 'L' 'H']


Унікальні значення в 'Country Code':
['Nor' 'Srb' 'Unknown' 'Mne' 'Svk' 'Fra' 'Esp' 'Hrv' 'Deu' 'Arm' 'Geo'
 'Gbr' 'Svn' 'Rou' 'Pol' 'Lux' 'Cyp' 'Bel' 'Ltu' 'Rus' 'Mlt' 'Ukr' 'Cze'
 'Prt' 'Blr' 'Est' 'Aut' 'Mkd' 'Smr' 'Nld' 'Che' 'Hun' 'Lva' 'Bgr' 'Ita'
 'Irl' 'And' 'Lie' 'Fin' 'Alb' 'Swe' 'Bih' 'Dnk' 'Mco' 'Isl' 'Grc']


Унікальні значення в 'Sales Channel':
['Online' 'Offline']

In [19]:
print("✅ Дублікатів:", df_events.duplicated().sum())

✅ Дублікатів: 0

In [20]:
df_events["Order Date"].min(), df_events["Order Date"].max()

(Timestamp('2010-01-01 00:00:00'), Timestamp('2017-07-23 00:00:00'))

 ***🔷 Досліди дані на наявність аномалій. Якщо є, спробуй зрозуміти причини.***

In [21]:
df_events.describe()

,Order ID,Order Date,Ship Date,Product ID,Units Sold,Unit Price,Unit Cost
count,1.328000e+03,1328,1328,1328.000000,1328.000000,1328.000000,1328.000000
mean,5.416231e+08,2013-10-11 22:28:54.939759104,2013-11-05 17:22:02.891566336,5787.775602,4952.201807,264.913245,187.211521
min,1.006406e+08,2010-01-01 00:00:00,2010-01-10 00:00:00,1270.000000,2.000000,9.330000,6.920000
25%,3.213291e+08,2011-12-14 06:00:00,2012-01-02 00:00:00,3127.000000,2356.750000,81.730000,35.840000
50%,5.399925e+08,2013-10-15 12:00:00,2013-11-05 12:00:00,5988.000000,4962.000000,154.060000,97.440000
75%,7.547357e+08,2015-08-29 12:00:00,2015-10-04 18:00:00,8681.000000,7459.500000,437.200000,263.330000
max,9.998797e+08,2017-07-23 00:00:00,2017-08-31 00:00:00,8969.000000,9999.000000,668.270000,524.960000
std,2.573496e+08,NaN,NaN,2820.635702,2905.198996,217.386320,176.187801

In [22]:
df_events[df_events["Ship Date"]< df_events["Order Date"]]

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date, Order Priority, Country Code, Product ID, Sales Channel, Units Sold, Unit Price, Unit Cost]
Index: []

In [23]:
df_events[df_events["Unit Cost"] > df_events["Unit Price"]]

Empty DataFrame
Columns: [Order ID, Order Date, Ship Date, Order Priority, Country Code, Product ID, Sales Channel, Units Sold, Unit Price, Unit Cost]
Index: []

✅ Аномалій в df_events - не виявлено.

Перевірка на викиди

In [28]:
Q1 = np.percentile(df_events['Units Sold'], 25)
Q3 = np.percentile(df_events['Units Sold'], 75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = [x for x in df_events['Units Sold'] if x < lower_bound or x > upper_bound]
print("Викиди Units Sold':", outliers)

Викиди Units Sold': []

In [27]:
Q1_price = np.percentile(df_events['Unit Price'], 25)
Q3_price = np.percentile(df_events['Unit Price'], 75)

IQR_price = Q3_price - Q1_price

lower_bound_price = Q1 - 1.5 * IQR_price
upper_bound_price = Q3 + 1.5 * IQR_price

outliers_price = [x for x in df_events['Unit Price'] if x < lower_bound_price or x > upper_bound_price]
print("Викиди Unit Price:", outliers_price)

Викиди Unit Price: [205.7, 205.7, 668.27, 109.28, 47.45, 651.21, 9.33, 154.06, 255.28, 205.7, 668.27, 421.89, 9.33, 255.28, 109.28, 668.27, 255.28, 109.28, 255.28, 421.89, 9.33, 255.28, 651.21, 437.2, 9.33, 651.21, 9.33, 152.58, 205.7, 152.58, 81.73, 81.73, 9.33, 9.33, 47.45, 47.45, 47.45, 47.45, 255.28, 205.7, 47.45, 152.58, 205.7, 255.28, 154.06, 9.33, 255.28, 255.28, 668.27, 651.21, 47.45, 81.73, 668.27, 154.06, 651.21, 81.73, 81.73, 437.2, 81.73, 154.06, 109.28, 47.45, 152.58, 651.21, 109.28, 437.2, 154.06, 437.2, 81.73, 255.28, 109.28, 668.27, 9.33, 668.27, 668.27, 205.7, 255.28, 651.21, 154.06, 437.2, 437.2, 651.21, 668.27, 651.21, 437.2, 255.28, 421.89, 109.28, 651.21, 9.33, 437.2, 9.33, 109.28, 255.28, 152.58, 9.33, 421.89, 651.21, 81.73, 437.2, 421.89, 109.28, 47.45, 152.58, 651.21, 421.89, 109.28, 651.21, 651.21, 255.28, 421.89, 421.89, 9.33, 109.28, 205.7, 255.28, 437.2, 668.27, 205.7, 109.28, 421.89, 668.27, 437.2, 47.45, 154.06, 651.21, 9.33, 651.21, 152.58, 437.2, 109.28, 255.28, 154.06, 668.27, 81.73, 9.33, 154.06, 651.21, 437.2, 9.33, 109.28, 651.21, 152.58, 47.45, 109.28, 47.45, 9.33, 47.45, 437.2, 668.27, 205.7, 81.73, 255.28, 81.73, 205.7, 668.27, 152.58, 421.89, 255.28, 668.27, 651.21, 152.58, 437.2, 255.28, 205.7, 651.21, 154.06, 437.2, 437.2, 651.21, 205.7, 437.2, 109.28, 651.21, 152.58, 651.21, 47.45, 421.89, 152.58, 152.58, 81.73, 154.06, 421.89, 651.21, 47.45, 255.28, 421.89, 205.7, 109.28, 255.28, 47.45, 9.33, 651.21, 437.2, 421.89, 154.06, 437.2, 47.45, 109.28, 109.28, 437.2, 668.27, 651.21, 109.28, 437.2, 109.28, 651.21, 47.45, 81.73, 651.21, 651.21, 668.27, 47.45, 9.33, 651.21, 205.7, 47.45, 47.45, 81.73, 437.2, 255.28, 47.45, 421.89, 81.73, 437.2, 651.21, 154.06, 9.33, 109.28, 109.28, 421.89, 109.28, 152.58, 255.28, 47.45, 651.21, 152.58, 651.21, 651.21, 154.06, 437.2, 109.28, 668.27, 9.33, 81.73, 9.33, 109.28, 255.28, 47.45, 651.21, 47.45, 81.73, 9.33, 109.28, 152.58, 152.58, 437.2, 668.27, 668.27, 651.21, 47.45, 152.58, 9.33, 421.89, 205.7, 81.73, 152.58, 109.28, 255.28, 9.33, 205.7, 255.28, 152.58, 205.7, 205.7, 152.58, 651.21, 437.2, 437.2, 154.06, 81.73, 437.2, 154.06, 81.73, 81.73, 255.28, 651.21, 421.89, 437.2, 668.27, 9.33, 47.45, 152.58, 9.33, 437.2, 81.73, 9.33, 255.28, 255.28, 154.06, 109.28, 437.2, 9.33, 255.28, 255.28, 81.73, 9.33, 154.06, 205.7, 81.73, 255.28, 9.33, 152.58, 47.45, 668.27, 9.33, 81.73, 81.73, 437.2, 9.33, 81.73, 47.45, 437.2, 47.45, 9.33, 651.21, 255.28, 152.58, 255.28, 47.45, 205.7, 47.45, 668.27, 205.7, 205.7, 109.28, 437.2, 47.45, 437.2, 255.28, 437.2, 651.21, 205.7, 437.2, 421.89, 109.28, 81.73, 437.2, 437.2, 651.21, 152.58, 651.21, 152.58, 651.21, 651.21, 47.45, 421.89, 154.06, 437.2, 152.58, 255.28, 421.89, 437.2, 437.2, 81.73, 152.58, 109.28, 437.2, 651.21, 81.73, 81.73, 9.33, 154.06, 47.45, 651.21, 81.73, 109.28, 81.73, 437.2, 47.45, 109.28, 255.28, 152.58, 109.28, 255.28, 154.06, 255.28, 205.7, 154.06, 9.33, 437.2, 255.28, 668.27, 651.21, 255.28, 47.45, 81.73, 651.21, 109.28, 109.28, 437.2, 47.45, 109.28, 668.27, 109.28, 421.89, 437.2, 255.28, 109.28, 9.33, 81.73, 109.28, 668.27, 154.06, 9.33, 651.21, 437.2, 437.2, 81.73, 154.06, 81.73, 154.06, 81.73, 152.58, 437.2, 651.21, 205.7, 152.58, 205.7, 154.06, 205.7, 81.73, 9.33, 109.28, 9.33, 154.06, 668.27, 9.33, 47.45, 81.73, 109.28, 81.73, 81.73, 47.45, 255.28, 205.7, 255.28, 154.06, 9.33, 152.58, 205.7, 205.7, 154.06, 152.58, 255.28, 255.28, 152.58, 154.06, 205.7, 154.06, 154.06, 81.73, 651.21, 81.73, 651.21, 421.89, 205.7, 255.28, 154.06, 9.33, 47.45, 255.28, 152.58, 255.28, 154.06, 47.45, 152.58, 437.2, 421.89, 668.27, 421.89, 205.7, 47.45, 651.21, 47.45, 152.58, 651.21, 152.58, 81.73, 205.7, 109.28, 47.45, 47.45, 651.21, 651.21, 437.2, 651.21, 81.73, 47.45, 47.45, 421.89, 421.89, 152.58, 81.73, 81.73, 47.45, 205.7, 9.33, 255.28, 205.7, 205.7, 47.45, 255.28, 255.28, 668.27, 205.7, 651.21, 81.73, 205.7, 154.06, 9.33, 437.2, 421.89, 152.58, 205.7, 437.2, 255.28, 9.33, 154.06, 205.7, 154.06, 81.73, 651.21, 421.89, 651.21, 421.89, 255.28, 9.33, 81.73, 255.28, 421.89, 668.27, 152.58, 154.06, 9.33, 81.73, 81.73, 109.28, 255.28, 651.21, 154.06, 9.33, 421.89, 205.7, 47.45, 154.06, 255.28, 109.28, 9.33, 255.28, 81.73, 9.33, 109.28, 152.58, 154.06, 47.45, 152.58, 205.7, 437.2, 47.45, 81.73, 255.28, 9.33, 255.28, 152.58, 205.7, 255.28, 9.33, 421.89, 205.7, 651.21, 152.58, 81.73, 437.2, 154.06, 9.33, 152.58, 154.06, 152.58, 154.06, 668.27, 205.7, 47.45, 154.06, 9.33, 668.27, 255.28, 109.28, 421.89, 437.2, 421.89, 152.58, 205.7, 421.89, 109.28, 152.58, 152.58, 109.28, 109.28, 81.73, 47.45, 152.58, 47.45, 651.21, 668.27, 421.89, 651.21, 109.28, 651.21, 154.06, 421.89, 152.58, 668.27, 421.89, 651.21, 668.27, 9.33, 152.58, 421.89, 205.7, 152.58, 205.7, 109.28, 651.21, 651.21, 437.2, 109.28, 109.28, 154.06, 109.28, 255.28, 205.7, 421.89, 668.27, 255.28, 152.58, 437.2, 109.28, 9.33, 154.06, 81.73, 651.21, 109.28, 255.28, 421.89, 421.89, 668.27, 651.21, 47.45, 154.06, 81.73, 152.58, 109.28, 109.28, 437.2, 47.45, 421.89, 668.27, 81.73, 109.28, 421.89, 81.73, 668.27, 81.73, 205.7, 81.73, 9.33, 152.58, 668.27, 651.21, 668.27, 437.2, 255.28, 205.7, 421.89, 421.89, 81.73, 205.7, 47.45, 47.45, 154.06, 205.7, 205.7, 154.06, 154.06, 651.21, 81.73, 109.28, 255.28, 47.45, 9.33, 437.2, 152.58, 205.7, 255.28, 668.27, 81.73, 668.27, 154.06, 205.7, 668.27, 437.2, 152.58, 651.21, 651.21, 81.73, 437.2, 81.73, 421.89, 9.33, 154.06, 9.33, 255.28, 205.7, 205.7, 47.45, 651.21, 152.58, 668.27, 668.27, 651.21, 437.2, 152.58, 152.58, 668.27, 152.58, 651.21, 205.7, 255.28, 81.73, 81.73, 81.73, 9.33, 205.7, 152.58, 109.28, 81.73, 81.73, 152.58, 81.73, 47.45, 81.73, 421.89, 255.28, 152.58, 81.73, 9.33, 47.45, 47.45, 9.33, 47.45, 109.28, 9.33, 651.21, 651.21, 109.28, 81.73, 421.89, 81.73, 9.33, 154.06, 437.2, 47.45, 668.27, 154.06, 255.28, 9.33, 421.89, 255.28, 152.58, 437.2, 154.06, 421.89, 437.2, 205.7, 421.89, 651.21, 668.27, 109.28, 9.33, 651.21, 651.21, 437.2, 81.73, 109.28, 205.7, 81.73, 437.2, 421.89, 81.73, 651.21, 154.06, 9.33, 255.28, 255.28, 255.28, 421.89, 421.89, 109.28, 421.89, 109.28, 9.33, 81.73, 9.33, 205.7, 154.06, 152.58, 437.2, 255.28, 421.89, 437.2, 81.73, 9.33, 47.45, 205.7, 255.28, 651.21, 9.33, 651.21, 47.45, 47.45, 421.89, 421.89, 9.33, 81.73, 651.21, 421.89, 421.89, 205.7, 255.28, 47.45, 255.28, 109.28, 651.21, 47.45, 154.06, 255.28, 154.06, 205.7, 152.58, 47.45, 47.45, 81.73, 651.21, 152.58, 668.27, 205.7, 9.33, 668.27, 651.21, 668.27, 437.2, 109.28, 651.21, 421.89, 421.89, 9.33, 9.33, 668.27, 205.7, 81.73, 255.28, 81.73, 421.89, 9.33, 437.2, 154.06, 154.06, 651.21, 668.27, 205.7, 668.27, 437.2, 668.27, 154.06, 47.45, 154.06, 421.89, 47.45, 437.2, 109.28, 255.28, 109.28, 205.7, 668.27, 154.06, 668.27, 437.2, 109.28, 668.27, 154.06, 109.28, 421.89, 668.27, 421.89, 437.2, 421.89, 421.89, 255.28, 255.28, 437.2, 437.2, 205.7, 651.21, 421.89, 421.89, 154.06, 154.06, 81.73, 81.73, 81.73, 668.27, 152.58, 47.45, 9.33, 668.27, 154.06, 668.27, 9.33, 9.33, 9.33, 668.27, 109.28, 109.28, 47.45, 668.27, 109.28, 47.45, 205.7, 154.06, 9.33, 81.73, 154.06, 651.21, 651.21, 109.28, 9.33, 255.28, 152.58, 9.33, 154.06, 152.58, 668.27, 9.33, 255.28, 421.89, 154.06, 437.2, 154.06, 437.2, 651.21, 421.89, 47.45, 421.89, 205.7, 205.7, 651.21, 47.45, 668.27, 152.58, 205.7, 255.28, 421.89, 668.27, 205.7, 152.58, 154.06, 47.45, 437.2, 154.06, 109.28, 154.06, 109.28, 437.2, 152.58, 421.89, 651.21, 109.28, 255.28, 9.33, 152.58, 255.28, 9.33, 9.33, 651.21, 81.73, 109.28, 152.58, 9.33, 421.89, 47.45, 668.27, 154.06, 651.21, 668.27, 154.06, 47.45, 109.28, 81.73, 81.73, 421.89, 651.21, 205.7, 255.28, 437.2, 152.58, 9.33, 668.27, 668.27, 109.28, 152.58, 154.06, 651.21, 154.06, 205.7, 47.45, 437.2, 9.33, 9.33, 255.28, 255.28, 651.21, 154.06, 421.89, 437.2, 109.28, 421.89, 109.28, 421.89, 152.58, 152.58, 668.27, 47.45, 152.58, 81.73, 437.2, 9.33, 205.7, 205.7, 668.27, 47.45, 421.89, 47.45, 47.45, 47.45, 205.7, 651.21, 109.28, 668.27, 81.73, 154.06, 437.2, 154.06, 154.06, 437.2, 255.28, 205.7, 154.06, 437.2, 205.7, 9.33, 437.2, 421.89, 437.2, 9.33, 154.06, 154.06, 154.06, 651.21, 437.2, 152.58, 421.89, 668.27, 437.2, 651.21, 109.28, 421.89, 47.45, 255.28, 437.2, 255.28, 668.27, 437.2, 9.33, 437.2, 47.45, 205.7, 668.27, 81.73, 668.27, 437.2, 668.27, 47.45, 255.28, 81.73, 109.28, 81.73, 668.27, 154.06, 152.58, 47.45, 255.28, 421.89, 668.27, 437.2, 152.58, 421.89, 154.06, 421.89, 651.21, 9.33, 255.28, 255.28, 437.2, 81.73, 205.7, 651.21, 651.21, 437.2, 47.45, 651.21, 81.73, 152.58, 47.45, 651.21, 421.89, 421.89, 668.27, 47.45, 651.21, 421.89, 651.21, 668.27, 109.28, 9.33, 668.27, 255.28, 668.27, 668.27, 47.45, 9.33, 421.89, 47.45, 421.89, 81.73, 437.2, 47.45, 9.33, 255.28, 109.28, 651.21, 152.58, 651.21, 47.45, 651.21, 152.58, 651.21, 421.89, 109.28, 651.21, 154.06, 437.2, 205.7, 9.33, 668.27, 255.28, 437.2, 154.06, 47.45, 205.7, 651.21, 9.33, 9.33, 437.2, 154.06, 421.89, 651.21, 9.33, 205.7, 668.27, 205.7, 47.45, 109.28, 109.28, 421.89, 437.2, 205.7, 437.2, 47.45, 9.33, 81.73, 421.89, 437.2, 255.28, 154.06, 109.28, 154.06, 421.89, 81.73, 152.58, 109.28, 9.33, 421.89, 255.28, 152.58, 255.28, 154.06, 109.28, 668.27, 109.28, 154.06, 651.21, 47.45, 109.28, 255.28, 154.06, 205.7, 421.89, 47.45, 421.89, 205.7, 421.89, 47.45, 109.28, 47.45, 81.73, 81.73, 154.06, 109.28, 154.06, 47.45, 47.45, 81.73, 154.06, 154.06, 109.28, 81.73, 205.7, 154.06, 81.73, 152.58, 154.06, 437.2, 152.58, 255.28, 421.89, 47.45, 205.7, 152.58, 47.45, 47.45, 421.89, 152.58, 47.45, 437.2, 152.58, 152.58, 668.27, 154.06, 81.73, 255.28, 154.06, 152.58, 205.7, 47.45, 205.7, 205.7, 9.33, 421.89, 81.73, 154.06, 152.58, 154.06, 421.89, 668.27, 421.89, 668.27, 152.58, 205.7, 154.06, 152.58, 47.45, 109.28, 9.33, 154.06, 651.21, 47.45, 152.58, 255.28, 421.89, 255.28, 81.73, 437.2, 47.45, 152.58, 651.21, 47.45, 205.7, 421.89, 154.06, 205.7, 81.73, 651.21, 668.27, 205.7, 9.33, 109.28, 668.27, 668.27, 9.33, 154.06, 81.73, 47.45, 9.33, 47.45, 255.28, 437.2, 668.27]

In [26]:
Q1_cost = np.percentile(df_events['Unit Cost'], 25)
Q3_cost = np.percentile(df_events['Unit Cost'], 75)

IQR_cost = Q3_cost - Q1_cost

lower_bound_cost = Q1 - 1.5 * IQR_cost
upper_bound_cost = Q3 + 1.5 * IQR_cost

outliers_price = [x for x in df_events['Unit Cost'] if x < lower_bound_price or x > upper_bound_price]
print("Викиди Unit Cost:", outliers_price)

Викиди Unit Cost: [117.11, 117.11, 502.54, 35.84, 31.79, 524.96, 6.92, 90.93, 159.42, 117.11, 502.54, 364.69, 6.92, 159.42, 35.84, 502.54, 159.42, 35.84, 159.42, 364.69, 6.92, 159.42, 524.96, 263.33, 6.92, 524.96, 6.92, 97.44, 117.11, 97.44, 56.67, 56.67, 6.92, 6.92, 31.79, 31.79, 31.79, 31.79, 159.42, 117.11, 31.79, 97.44, 117.11, 159.42, 90.93, 6.92, 159.42, 159.42, 502.54, 524.96, 31.79, 56.67, 502.54, 90.93, 524.96, 56.67, 56.67, 263.33, 56.67, 90.93, 35.84, 31.79, 97.44, 524.96, 35.84, 263.33, 90.93, 263.33, 56.67, 159.42, 35.84, 502.54, 6.92, 502.54, 502.54, 117.11, 159.42, 524.96, 90.93, 263.33, 263.33, 524.96, 502.54, 524.96, 263.33, 159.42, 364.69, 35.84, 524.96, 6.92, 263.33, 6.92, 35.84, 159.42, 97.44, 6.92, 364.69, 524.96, 56.67, 263.33, 364.69, 35.84, 31.79, 97.44, 524.96, 364.69, 35.84, 524.96, 524.96, 159.42, 364.69, 364.69, 6.92, 35.84, 117.11, 159.42, 263.33, 502.54, 117.11, 35.84, 364.69, 502.54, 263.33, 31.79, 90.93, 524.96, 6.92, 524.96, 97.44, 263.33, 35.84, 159.42, 90.93, 502.54, 56.67, 6.92, 90.93, 524.96, 263.33, 6.92, 35.84, 524.96, 97.44, 31.79, 35.84, 31.79, 6.92, 31.79, 263.33, 502.54, 117.11, 56.67, 159.42, 56.67, 117.11, 502.54, 97.44, 364.69, 159.42, 502.54, 524.96, 97.44, 263.33, 159.42, 117.11, 524.96, 90.93, 263.33, 263.33, 524.96, 117.11, 263.33, 35.84, 524.96, 97.44, 524.96, 31.79, 364.69, 97.44, 97.44, 56.67, 90.93, 364.69, 524.96, 31.79, 159.42, 364.69, 117.11, 35.84, 159.42, 31.79, 6.92, 524.96, 263.33, 364.69, 90.93, 263.33, 31.79, 35.84, 35.84, 263.33, 502.54, 524.96, 35.84, 263.33, 35.84, 524.96, 31.79, 56.67, 524.96, 524.96, 502.54, 31.79, 6.92, 524.96, 117.11, 31.79, 31.79, 56.67, 263.33, 159.42, 31.79, 364.69, 56.67, 263.33, 524.96, 90.93, 6.92, 35.84, 35.84, 364.69, 35.84, 97.44, 159.42, 31.79, 524.96, 97.44, 524.96, 524.96, 90.93, 263.33, 35.84, 502.54, 6.92, 56.67, 6.92, 35.84, 159.42, 31.79, 524.96, 31.79, 56.67, 6.92, 35.84, 97.44, 97.44, 263.33, 502.54, 502.54, 524.96, 31.79, 97.44, 6.92, 364.69, 117.11, 56.67, 97.44, 35.84, 159.42, 6.92, 117.11, 159.42, 97.44, 117.11, 117.11, 97.44, 524.96, 263.33, 263.33, 90.93, 56.67, 263.33, 90.93, 56.67, 56.67, 159.42, 524.96, 364.69, 263.33, 502.54, 6.92, 31.79, 97.44, 6.92, 263.33, 56.67, 6.92, 159.42, 159.42, 90.93, 35.84, 263.33, 6.92, 159.42, 159.42, 56.67, 6.92, 90.93, 117.11, 56.67, 159.42, 6.92, 97.44, 31.79, 502.54, 6.92, 56.67, 56.67, 263.33, 6.92, 56.67, 31.79, 263.33, 31.79, 6.92, 524.96, 159.42, 97.44, 159.42, 31.79, 117.11, 31.79, 502.54, 117.11, 117.11, 35.84, 263.33, 31.79, 263.33, 159.42, 263.33, 524.96, 117.11, 263.33, 364.69, 35.84, 56.67, 263.33, 263.33, 524.96, 97.44, 524.96, 97.44, 524.96, 524.96, 31.79, 364.69, 90.93, 263.33, 97.44, 159.42, 364.69, 263.33, 263.33, 56.67, 97.44, 35.84, 263.33, 524.96, 56.67, 56.67, 6.92, 90.93, 31.79, 524.96, 56.67, 35.84, 56.67, 263.33, 31.79, 35.84, 159.42, 97.44, 35.84, 159.42, 90.93, 159.42, 117.11, 90.93, 6.92, 263.33, 159.42, 502.54, 524.96, 159.42, 31.79, 56.67, 524.96, 35.84, 35.84, 263.33, 31.79, 35.84, 502.54, 35.84, 364.69, 263.33, 159.42, 35.84, 6.92, 56.67, 35.84, 502.54, 90.93, 6.92, 524.96, 263.33, 263.33, 56.67, 90.93, 56.67, 90.93, 56.67, 97.44, 263.33, 524.96, 117.11, 97.44, 117.11, 90.93, 117.11, 56.67, 6.92, 35.84, 6.92, 90.93, 502.54, 6.92, 31.79, 56.67, 35.84, 56.67, 56.67, 31.79, 159.42, 117.11, 159.42, 90.93, 6.92, 97.44, 117.11, 117.11, 90.93, 97.44, 159.42, 159.42, 97.44, 90.93, 117.11, 90.93, 90.93, 56.67, 524.96, 56.67, 524.96, 364.69, 117.11, 159.42, 90.93, 6.92, 31.79, 159.42, 97.44, 159.42, 90.93, 31.79, 97.44, 263.33, 364.69, 502.54, 364.69, 117.11, 31.79, 524.96, 31.79, 97.44, 524.96, 97.44, 56.67, 117.11, 35.84, 31.79, 31.79, 524.96, 524.96, 263.33, 524.96, 56.67, 31.79, 31.79, 364.69, 364.69, 97.44, 56.67, 56.67, 31.79, 117.11, 6.92, 159.42, 117.11, 117.11, 31.79, 159.42, 159.42, 502.54, 117.11, 524.96, 56.67, 117.11, 90.93, 6.92, 263.33, 364.69, 97.44, 117.11, 263.33, 159.42, 6.92, 90.93, 117.11, 90.93, 56.67, 524.96, 364.69, 524.96, 364.69, 159.42, 6.92, 56.67, 159.42, 364.69, 502.54, 97.44, 90.93, 6.92, 56.67, 56.67, 35.84, 159.42, 524.96, 90.93, 6.92, 364.69, 117.11, 31.79, 90.93, 159.42, 35.84, 6.92, 159.42, 56.67, 6.92, 35.84, 97.44, 90.93, 31.79, 97.44, 117.11, 263.33, 31.79, 56.67, 159.42, 6.92, 159.42, 97.44, 117.11, 159.42, 6.92, 364.69, 117.11, 524.96, 97.44, 56.67, 263.33, 90.93, 6.92, 97.44, 90.93, 97.44, 90.93, 502.54, 117.11, 31.79, 90.93, 6.92, 502.54, 159.42, 35.84, 364.69, 263.33, 364.69, 97.44, 117.11, 364.69, 35.84, 97.44, 97.44, 35.84, 35.84, 56.67, 31.79, 97.44, 31.79, 524.96, 502.54, 364.69, 524.96, 35.84, 524.96, 90.93, 364.69, 97.44, 502.54, 364.69, 524.96, 502.54, 6.92, 97.44, 364.69, 117.11, 97.44, 117.11, 35.84, 524.96, 524.96, 263.33, 35.84, 35.84, 90.93, 35.84, 159.42, 117.11, 364.69, 502.54, 159.42, 97.44, 263.33, 35.84, 6.92, 90.93, 56.67, 524.96, 35.84, 159.42, 364.69, 364.69, 502.54, 524.96, 31.79, 90.93, 56.67, 97.44, 35.84, 35.84, 263.33, 31.79, 364.69, 502.54, 56.67, 35.84, 364.69, 56.67, 502.54, 56.67, 117.11, 56.67, 6.92, 97.44, 502.54, 524.96, 502.54, 263.33, 159.42, 117.11, 364.69, 364.69, 56.67, 117.11, 31.79, 31.79, 90.93, 117.11, 117.11, 90.93, 90.93, 524.96, 56.67, 35.84, 159.42, 31.79, 6.92, 263.33, 97.44, 117.11, 159.42, 502.54, 56.67, 502.54, 90.93, 117.11, 502.54, 263.33, 97.44, 524.96, 524.96, 56.67, 263.33, 56.67, 364.69, 6.92, 90.93, 6.92, 159.42, 117.11, 117.11, 31.79, 524.96, 97.44, 502.54, 502.54, 524.96, 263.33, 97.44, 97.44, 502.54, 97.44, 524.96, 117.11, 159.42, 56.67, 56.67, 56.67, 6.92, 117.11, 97.44, 35.84, 56.67, 56.67, 97.44, 56.67, 31.79, 56.67, 364.69, 159.42, 97.44, 56.67, 6.92, 31.79, 31.79, 6.92, 31.79, 35.84, 6.92, 524.96, 524.96, 35.84, 56.67, 364.69, 56.67, 6.92, 90.93, 263.33, 31.79, 502.54, 90.93, 159.42, 6.92, 364.69, 159.42, 97.44, 263.33, 90.93, 364.69, 263.33, 117.11, 364.69, 524.96, 502.54, 35.84, 6.92, 524.96, 524.96, 263.33, 56.67, 35.84, 117.11, 56.67, 263.33, 364.69, 56.67, 524.96, 90.93, 6.92, 159.42, 159.42, 159.42, 364.69, 364.69, 35.84, 364.69, 35.84, 6.92, 56.67, 6.92, 117.11, 90.93, 97.44, 263.33, 159.42, 364.69, 263.33, 56.67, 6.92, 31.79, 117.11, 159.42, 524.96, 6.92, 524.96, 31.79, 31.79, 364.69, 364.69, 6.92, 56.67, 524.96, 364.69, 364.69, 117.11, 159.42, 31.79, 159.42, 35.84, 524.96, 31.79, 90.93, 159.42, 90.93, 117.11, 97.44, 31.79, 31.79, 56.67, 524.96, 97.44, 502.54, 117.11, 6.92, 502.54, 524.96, 502.54, 263.33, 35.84, 524.96, 364.69, 364.69, 6.92, 6.92, 502.54, 117.11, 56.67, 159.42, 56.67, 364.69, 6.92, 263.33, 90.93, 90.93, 524.96, 502.54, 117.11, 502.54, 263.33, 502.54, 90.93, 31.79, 90.93, 364.69, 31.79, 263.33, 35.84, 159.42, 35.84, 117.11, 502.54, 90.93, 502.54, 263.33, 35.84, 502.54, 90.93, 35.84, 364.69, 502.54, 364.69, 263.33, 364.69, 364.69, 159.42, 159.42, 263.33, 263.33, 117.11, 524.96, 364.69, 364.69, 90.93, 90.93, 56.67, 56.67, 56.67, 502.54, 97.44, 31.79, 6.92, 502.54, 90.93, 502.54, 6.92, 6.92, 6.92, 502.54, 35.84, 35.84, 31.79, 502.54, 35.84, 31.79, 117.11, 90.93, 6.92, 56.67, 90.93, 524.96, 524.96, 35.84, 6.92, 159.42, 97.44, 6.92, 90.93, 97.44, 502.54, 6.92, 159.42, 364.69, 90.93, 263.33, 90.93, 263.33, 524.96, 364.69, 31.79, 364.69, 117.11, 117.11, 524.96, 31.79, 502.54, 97.44, 117.11, 159.42, 364.69, 502.54, 117.11, 97.44, 90.93, 31.79, 263.33, 90.93, 35.84, 90.93, 35.84, 263.33, 97.44, 364.69, 524.96, 35.84, 159.42, 6.92, 97.44, 159.42, 6.92, 6.92, 524.96, 56.67, 35.84, 97.44, 6.92, 364.69, 31.79, 502.54, 90.93, 524.96, 502.54, 90.93, 31.79, 35.84, 56.67, 56.67, 364.69, 524.96, 117.11, 159.42, 263.33, 97.44, 6.92, 502.54, 502.54, 35.84, 97.44, 90.93, 524.96, 90.93, 117.11, 31.79, 263.33, 6.92, 6.92, 159.42, 159.42, 524.96, 90.93, 364.69, 263.33, 35.84, 364.69, 35.84, 364.69, 97.44, 97.44, 502.54, 31.79, 97.44, 56.67, 263.33, 6.92, 117.11, 117.11, 502.54, 31.79, 364.69, 31.79, 31.79, 31.79, 117.11, 524.96, 35.84, 502.54, 56.67, 90.93, 263.33, 90.93, 90.93, 263.33, 159.42, 117.11, 90.93, 263.33, 117.11, 6.92, 263.33, 364.69, 263.33, 6.92, 90.93, 90.93, 90.93, 524.96, 263.33, 97.44, 364.69, 502.54, 263.33, 524.96, 35.84, 364.69, 31.79, 159.42, 263.33, 159.42, 502.54, 263.33, 6.92, 263.33, 31.79, 117.11, 502.54, 56.67, 502.54, 263.33, 502.54, 31.79, 159.42, 56.67, 35.84, 56.67, 502.54, 90.93, 97.44, 31.79, 159.42, 364.69, 502.54, 263.33, 97.44, 364.69, 90.93, 364.69, 524.96, 6.92, 159.42, 159.42, 263.33, 56.67, 117.11, 524.96, 524.96, 263.33, 31.79, 524.96, 56.67, 97.44, 31.79, 524.96, 364.69, 364.69, 502.54, 31.79, 524.96, 364.69, 524.96, 502.54, 35.84, 6.92, 502.54, 159.42, 502.54, 502.54, 31.79, 6.92, 364.69, 31.79, 364.69, 56.67, 263.33, 31.79, 6.92, 159.42, 35.84, 524.96, 97.44, 524.96, 31.79, 524.96, 97.44, 524.96, 364.69, 35.84, 524.96, 90.93, 263.33, 117.11, 6.92, 502.54, 159.42, 263.33, 90.93, 31.79, 117.11, 524.96, 6.92, 6.92, 263.33, 90.93, 364.69, 524.96, 6.92, 117.11, 502.54, 117.11, 31.79, 35.84, 35.84, 364.69, 263.33, 117.11, 263.33, 31.79, 6.92, 56.67, 364.69, 263.33, 159.42, 90.93, 35.84, 90.93, 364.69, 56.67, 97.44, 35.84, 6.92, 364.69, 159.42, 97.44, 159.42, 90.93, 35.84, 502.54, 35.84, 90.93, 524.96, 31.79, 35.84, 159.42, 90.93, 117.11, 364.69, 31.79, 364.69, 117.11, 364.69, 31.79, 35.84, 31.79, 56.67, 56.67, 90.93, 35.84, 90.93, 31.79, 31.79, 56.67, 90.93, 90.93, 35.84, 56.67, 117.11, 90.93, 56.67, 97.44, 90.93, 263.33, 97.44, 159.42, 364.69, 31.79, 117.11, 97.44, 31.79, 31.79, 364.69, 97.44, 31.79, 263.33, 97.44, 97.44, 502.54, 90.93, 56.67, 159.42, 90.93, 97.44, 117.11, 31.79, 117.11, 117.11, 6.92, 364.69, 56.67, 90.93, 97.44, 90.93, 364.69, 502.54, 364.69, 502.54, 97.44, 117.11, 90.93, 97.44, 31.79, 35.84, 6.92, 90.93, 524.96, 31.79, 97.44, 159.42, 364.69, 159.42, 56.67, 263.33, 31.79, 97.44, 524.96, 31.79, 117.11, 364.69, 90.93, 117.11, 56.67, 524.96, 502.54, 117.11, 6.92, 35.84, 502.54, 502.54, 6.92, 90.93, 56.67, 31.79, 6.92, 31.79, 159.42, 263.33, 502.54]

## ***products***